name = "socialtide-astro-template"
compatibility_date = "2024-03-25"

vars = { 'ENVIRONMENT' = 'dev' }

[env.staging]
name = "socialtide-astro-template-preview"
routes = [
  { pattern = "preview-astro-template.socialtide.ai", custom_domain = true },
]
vars = { 'ENVIRONMENT' = 'staging' }

# Ends up being what DNS is pointed to
[env.production]
name = "socialtide-astro-template-production"
routes = [{ pattern = "astro-template.socialtide.ai", custom_domain = true }]
vars = { 'ENVIRONMENT' = 'production' }

[assets]
directory = "./dist"
not_found_handling = "404-page"
